### ISSUE TITLE
synchronous query

### ISSUE THREAD

**Issue by smhg** [djvirgen/virgen-acl#4]
I'm trying to use virgen-acl inside a (client-side) Handlebars template helper so my templates can contain something like:

```
{{#can "edit" blog}}<button>Edit</button>{{/can}}
```

The `can` helper gets the current user and queries the acl similar to:

```
acl.query(user, resource, action, function (err, allowed) {
  if (allowed) {
    return options.fn(self);
  }
});
```

This can not work however since Handlebars helpers can only return synchronous results.

Would you support turning `query` into a sync method if no callback is specified?
I'm happy to contribute.

**Comment by nervgh** [comment]
I have a backend on koa@2 which uses async functions (promises) and I'm viewing your package right now. It looks optimistic :+1: The slogan says

> Simple **in-memory** ACL for node.js apps

And I think why does "in-memory ACL" require callbacks? :smirk_cat: 
Oh, don't worry about that. These are just my minds :smile_cat:

**Comment by spruce-bruce** [comment]
It uses callbacks because it's possible to do async work in the callbacks. This lets you fetch things from the database yourself to do custom logic to determine if your role _really does_ have access to that resource.

**Comment by smhg** [comment]
I'm going to close this as I have no more use for this myself. Thanks for your feedback!
