### ISSUE TITLE
Inactive?

### ISSUE THREAD

**Issue by spruce-bruce** [djvirgen/virgen-acl#9]
Hi! I like this module and will probably be using it in an upcoming project.

Obviously this isn't something that has been actively worked on (not that it necessarily needs to be), but I'm wondering if, for example, I created a sensible PR would you review it, or is this module something that you aren't interested in maintaining?

If the former, I will happily use your module, if the latter I will fork and maintain separately.

**Comment by djvirgen** [comment]
Hello, @spruce-bruce ! Sure, I'd be happy to review a PR. You're right that this isn't actively in development, but I still use it in current projects.

**Comment by spruce-bruce** [comment]
Great thanks!
